{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cert-manager-google-cas-issuer.name" . }}
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
{{- end }}
