{{ if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-google-cas-issuer.serviceAccountName" . }}
  labels:
{{ include "cert-manager-google-cas-issuer.labels" . | indent 4 }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
