# This workflow runs unpriviledged unit tests.
name: e2e-tests
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-tags: true

    - id: go-version
      run: |
        make print-go-version >> "$GITHUB_OUTPUT"

    - uses: actions/setup-go@v5
      with:
        go-version: ${{ steps.go-version.outputs.result }}

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: 'projects/874174494201/locations/global/workloadIdentityPools/google-cas-issuer-e2e/providers/google-cas-issuer-e2e'
        service_account: 'google-cas-issuer-e2e@jetstack-cas.iam.gserviceaccount.com'

    - run: make test-e2e
      env:
        TEST_GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-artifacts
        path: _bin/artifacts
