# This workflow runs privileged e2e tests for trusted sources.
name: e2e-tests
on:
  push:
    branches:
      - main
  schedule:
    # At 03:23 on every 3rd day
    - cron: "23 3 */3 * *"

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19'

    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/874174494201/locations/global/workloadIdentityPools/google-cas-issuer-e2e/providers/google-cas-issuer-e2e'
        service_account: 'google-cas-issuer-e2e@jetstack-cas.iam.gserviceaccount.com'

    - name: Run e2e tests
      run: make e2e
      env:
        TEST_GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-logs
        path: _artifacts/e2e/logs
